# Generated by Django 2.2.5 on 2019-09-09 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentmodell',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='studentmodell',
            name='parent_id',
        ),
        migrations.AlterField(
            model_name='classmodell',
            name='class_id',
            field=models.AutoField(default='999', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parentmodell',
            name='parent_id',
            field=models.AutoField(auto_created=True, default='999', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_attendence',
            name='student_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.StudentModell'),
        ),
        migrations.AlterField(
            model_name='student_marks',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.StudentModell'),
        ),
        migrations.AlterField(
            model_name='studentmodell',
            name='student_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.ParentModell')),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.StudentModell')),
            ],
        ),
    ]
