# Generated by Django 2.2.5 on 2019-09-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190909_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodell',
            name='totalexammarks',
            field=models.IntegerField(choices=[(20, 20), (30, 30), (70, 70)]),
        ),
        migrations.AlterField(
            model_name='exammodell',
            name='typeexam',
            field=models.CharField(choices=[('Class Test', 'Class Test'), ('Unit Test', 'Unit Test'), ('Final Test', 'Final Test')], max_length=50),
        ),
    ]
