# Generated by Django 2.2.5 on 2019-09-09 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20190910_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentparent',
            name='parent_id',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='student.ParentModell'),
        ),
        migrations.AlterField(
            model_name='studentparent',
            name='student_id',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='student.StudentModell'),
        ),
    ]
