# Generated by Django 2.2.5 on 2019-09-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20190910_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_marks',
            name='pass_fail',
            field=models.CharField(choices=[('Pass', 'P'), ('Fail', 'F')], max_length=10),
        ),
    ]
