# Generated by Django 2.2.5 on 2019-09-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20190911_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STmapping',
        ),
    ]
