# Generated by Django 2.2.4 on 2019-09-09 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('exam_type', models.CharField(max_length=100)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.ClassTeacher')),
                ('student_roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Attendance')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Subject')),
            ],
        ),
    ]
