# Generated by Django 2.2.4 on 2019-09-09 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('total_marks', models.IntegerField()),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Subject')),
            ],
        ),
    ]
