# Generated by Django 2.2.4 on 2019-09-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='Sunday',
        ),
    ]
