# Generated by Django 2.2.5 on 2019-09-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentmodell',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentmodell',
            name='password',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
