# Generated by Django 2.2.5 on 2019-09-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodell',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
            preserve_default=False,
        ),
    ]
