# Generated by Django 2.2.5 on 2019-09-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentmodell_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodell',
            name='dob',
            field=models.IntegerField(max_length=50),
        ),
    ]
