# Generated by Django 2.2.5 on 2019-09-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20190909_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_attendence',
            old_name='noofdays_attended',
            new_name='attendence_percent',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='total_days',
        ),
    ]
