# Generated by Django 2.2.5 on 2019-09-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20190913_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodell',
            name='dob',
            field=models.CharField(max_length=50),
        ),
    ]
