# Generated by Django 2.2.5 on 2019-09-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190913_1724'),
        ('student', '0006_auto_20190913_2154'),
    ]

    operations = [
    ]
