# Generated by Django 2.2.5 on 2019-09-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_merge_20190914_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodell',
            name='gender',
        ),
    ]
