# Generated by Django 2.2.5 on 2019-09-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20190910_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodell',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
