# Generated by Django 2.2.5 on 2019-09-14 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20190914_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_attendence',
            name='April',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='August',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='December',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='February',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='January',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='July',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='June',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='March',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='May',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='November',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='October',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='September',
        ),
    ]
