# Generated by Django 2.2.5 on 2019-09-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20190914_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentmodell',
            name='email',
        ),
        migrations.RemoveField(
            model_name='parentmodell',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='April',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='August',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='December',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='February',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='January',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='July',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='June',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='March',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='May',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='November',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='October',
        ),
        migrations.RemoveField(
            model_name='student_attendence',
            name='September',
        ),
        migrations.AddField(
            model_name='studentmodell',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
            preserve_default=False,
        ),
    ]
