# Generated by Django 2.2.5 on 2019-09-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20190914_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentmodell',
            name='email',
            field=models.CharField(default='abc@gmail.com', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentmodell',
            name='mobile',
            field=models.CharField(default=9158814409, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentmodell',
            name='password',
            field=models.CharField(default='password', max_length=50),
            preserve_default=False,
        ),
    ]
