# Generated by Django 2.2.5 on 2019-09-15 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20190915_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentModell')),
            ],
        ),
    ]
