# Generated by Django 2.2.5 on 2019-09-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20190914_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentmodell',
            name='parent_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
